# Generated by Django 3.0.7 on 2020-06-09 20:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('hex_color', models.CharField(max_length=7)),
                ('num_weeks', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('weight', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('column_order_position', models.IntegerField()),
                ('year', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Team')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start_date', models.DateTimeField()),
                ('shift_end_date', models.DateTimeField()),
                ('is_backup', models.BooleanField(default=False)),
                ('is_night', models.BooleanField(default=False)),
                ('is_off', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_author', related_query_name='entry_author', to='server.TeamMember')),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Rotation')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Schedule')),
                ('team_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entry_team_member', related_query_name='schedule_entry_team_member', to='server.TeamMember')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start_date', models.DateTimeField()),
                ('shift_end_date', models.DateTimeField()),
                ('is_backup', models.BooleanField(default=False)),
                ('is_night', models.BooleanField(default=False)),
                ('is_off', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_author', related_query_name='change_author', to='server.TeamMember')),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Rotation')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Schedule')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_change_request_team_member', related_query_name='schedule_change_request_team_member', to='server.TeamMember')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Team'),
        ),
        migrations.AddField(
            model_name='rotation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Team'),
        ),
    ]
