# Generated by Django 3.0.7 on 2020-06-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
