# Generated by Django 3.0.7 on 2020-06-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20200611_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='column_order_position',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
