# Generated by Django 3.0.7 on 2020-06-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20200611_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotation',
            name='hex_color',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
