# Generated by Django 3.0.7 on 2020-06-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20200611_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotation',
            name='hex_color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
